title: <p align="center"> Smita Behera </p>
logo: /assets/img/Avatar.PNG

description:
  <p align="center">
  <a href="https://github.com/smitabehera">Resume</a> |
  <a href="https://github.com/smitabehera">LinkedIn</a> |
  <a href="https://github.com/smitabehera">GitHub</a>

show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
